/*
 * Copyright 2025 Jeff Hain
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package net.jolikit.bwd.impl.utils.graphics;

import java.util.Map;

/**
 * Map populate code generated by ScaledRectDrawingTest
 * with MAX_DELTA_COMPUTATION_MODE = true.
 */
public class ScaledRectDrawingTestGen {
    
    //--------------------------------------------------------------------------
    // CONSTRUCTORS
    //--------------------------------------------------------------------------
    
    private ScaledRectDrawingTestGen() {
    }
    
    //--------------------------------------------------------------------------
    // PUBLIC METHODS
    //--------------------------------------------------------------------------
    
    public static void populateMaxDeltaByCase(Map<String,Integer> m) {
        m.put("vsBack-resz-nonUni-(ABGR_P)-prl", 24);
        m.put("vsBack-resz-nonUni-(ABGR_P)-seq", 24);
        m.put("vsBack-resz-nonUni-(ARGB_N)-prl", 28);
        m.put("vsBack-resz-nonUni-(ARGB_N)-seq", 28);
        m.put("vsBack-resz-nonUni-(ARGB_P)-prl", 24);
        m.put("vsBack-resz-nonUni-(ARGB_P)-seq", 24);
        m.put("vsBack-resz-uni-(ABGR_P)-prl", 11);
        m.put("vsBack-resz-uni-(ABGR_P)-seq", 11);
        m.put("vsBack-resz-uni-(ARGB_N)-prl", 16);
        m.put("vsBack-resz-uni-(ARGB_N)-seq", 16);
        m.put("vsBack-resz-uni-(ARGB_P)-prl", 15);
        m.put("vsBack-resz-uni-(ARGB_P)-seq", 15);
        m.put("vsRef-copy-(ABGR_P)-prl", 0);
        m.put("vsRef-copy-(ABGR_P)-seq", 0);
        m.put("vsRef-copy-(ARGB_N)-prl", 0);
        m.put("vsRef-copy-(ARGB_N)-seq", 0);
        m.put("vsRef-copy-(ARGB_P)-prl", 0);
        m.put("vsRef-copy-(ARGB_P)-seq", 0);
        m.put("vsRef-resz-nonUni-(ABGR_P)-prl", 0);
        m.put("vsRef-resz-nonUni-(ABGR_P)-seq", 0);
        m.put("vsRef-resz-nonUni-(ARGB_N)-prl", 0);
        m.put("vsRef-resz-nonUni-(ARGB_N)-seq", 0);
        m.put("vsRef-resz-nonUni-(ARGB_P)-prl", 0);
        m.put("vsRef-resz-nonUni-(ARGB_P)-seq", 0);
        m.put("vsRef-resz-uni-(ABGR_P)-prl", 0);
        m.put("vsRef-resz-uni-(ABGR_P)-seq", 0);
        m.put("vsRef-resz-uni-(ARGB_N)-prl", 0);
        m.put("vsRef-resz-uni-(ARGB_N)-seq", 0);
        m.put("vsRef-resz-uni-(ARGB_P)-prl", 0);
        m.put("vsRef-resz-uni-(ARGB_P)-seq", 0);
    }
}
