/*
 * Copyright 2019 Jeff Hain
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Package for JavaFX binding.
 * Done with JavaFX 8.
 * 
 * TODO jfx Principal known issues or limitations:
 * - In JavaFX, (rectangular) bounds are not updated atomically, but are
 *   a composite of multiple values updated separately and with separate
 *   listeners, and invariants between related bounds are enforced
 *   asynchronously as well, which makes it easy to observe inconsistent values
 *   for bounds of a same entity or between bounds when the window moves or is
 *   resized. This binding tries to make up for that the best it can.
 *   In particular, it uses configured insets, instead of trying to read them
 *   from JavaFX API.
 * - By default using JavaFX internal API for font metrics, for computing them
 *   with the public API is very ugly and slow.
 * - Can have Stage.isMaximized() inconsistent with actual bounds.
 * - For some reason, when using ALT (or else?) as modifiers for key events,
 *   and even if also using SHIFT as secondary (in time) modifier,
 *   no key typed event is generated by JavaFX (and some inappropriate
 *   mouse entered/exited/moved events are generated "instead"),
 *   and as a result this binding doesn't generate them either.
 */
package net.jolikit.bwd.impl.jfx;
